#!/usr/bin/expect -f
set timeout 600
set server [lindex $argv 0]
set username [lindex $argv 1]
set root_password [lindex $argv 2]
set key [lindex $argv 3]
set try 0

set command_executed false

if { $username == "root" } {
        spawn ssh -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $username@$server
} elseif { [string match "" $key] } {
        spawn ssh -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $username@$server "su - root"
} else {
        spawn ssh -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i $key $username@$server "su - root"
}
expect {
        -re ".*Are you sure you want to continue connecting.*es.*o.*" {
                exp_send "yes\r"
                exp_continue
        }
        -re ".*assword:*" {
                if { $try > 0 } {
                        exp_send "\003\r"
                } else {
                        exp_send "$root_password\r"
                        set try [expr $try+1]
                        exp_continue
                }
        }
        -re ".*#.*|.*>.*" {
                if { $command_executed } {
                        exp_send "exit\r"
                } else {
                        exp_send "whoami\r"
                        set command_executed true
                        exp_continue
                }
        }
        eof
}
set iwant [lindex [split $expect_out(buffer) "\n"] 1]
if { [string match "root\r" $iwant] } {
        exit 0
} else {
        exit 1
}
expect eof
